### ISSUE TITLE
Advice on state management

### ISSUE THREAD

**Issue by grant-d** [metauto-ai/GPTSwarm#25]
This is one of the most approachable agent frameworks I have used. Thank you.

Would you mind giving me some advice on state management. I just need direction as there seem to be several ways of doing the same thing, and I don't want to start down the wrong (/unintended) path.

**Question**
I need agents to manage a hierarchy of objects. Which implies a user-navigable state machine.
_[edit] Simplified the question_

- For N states, would you use 1 _uber-agent_, or 1 _agent per state_
- Typically, no external tools needed, so I guess a `DirectAnswer`-type agent may suffice? Furthermore, I imagine a `swarm` would suffice (versus a DAG like `CoT` or `ToT`)
- Context/navigation state is truly global, ie not peculiar to each `agent.id`. Would you keep said state (somehow) in `globalMemory`, or as an `inputs[x]/outputs[x]` state that is flowed around, as extra properties in `executions {}` or in an `env` (per your crossword example)?

Thanks

**Comment by mczhuge** [comment]
Thanks! @grant-d This is a very great suggestion, would you like to contribute to this?

@Wenyi-AI-Wang any suggestion here?

**Comment by Wenyi-AI-Wang** [comment]
I may not be the best person to answer it. Maybe @Obs01ete can answer better. My opinion is that it's better to do it stateless, i.e., passing the state as input/output.  The global memory is designed to track information that is not considered part of the computational graphs.

**Comment by Obs01ete** [comment]
@grant-d Thank you for your feedback. The current implementation is practically limited to a single Swarm instance due to the state implementation as a singleton (GlobalMemory). The code was developed with research purposes in mind, not for production. Please let me know if you really need multiple instances of Swarm at the same time.
