### ISSUE TITLE
Numpy version issue

### ISSUE THREAD

**Issue by yl-miao** [metauto-ai/GPTSwarm#26]
Hi,

After testing, the [demo_swarm](https://github.com/metauto-ai/GPTSwarm/blob/main/notebooks/demo_swarm.ipynb) can be run in a newly-created Colab Notebook after `pip install gptswarm`, but cannot be run in a newly-created Python 3.10 environment by miniconda after `pip install gptswarm`. Please refer to the pictures:

<img width="948" alt="Pasted Graphic" src="https://github.com/metauto-ai/GPTSwarm/assets/54579689/744241a9-2562-4a1b-a619-b90a33c0bcd4">

<img width="881" alt="Pasted Graphic 1" src="https://github.com/metauto-ai/GPTSwarm/assets/54579689/4655cf59-d9df-4c2f-894a-99451fdb093f">

I suspect the reason might be: In Colab, although the default version for Python is 3.10, the default version for numpy is 1.25.2. However, in a newly-created conda Python 3.10 environment, during `pip install gptswarm`, it would install numpy version 2.0.0.

I wondered if this issue can be fixed by adding a restriction for numpy version in the "[pyproject.toml](https://github.com/metauto-ai/GPTSwarm/blob/main/pyproject.toml)" file, or it may be caused by something in the demo code, or by something else, I'm not entirely sure.

Thank you very much!

@Obs01ete 

The detailed output (After 'conda create -n tmpenv python=3.10' and 'pip install gptswarm' and the demo_swarm):
<img width="1105" alt="Pasted Graphic 2" src="https://github.com/metauto-ai/GPTSwarm/assets/54579689/3e26a462-a367-49b3-85ea-9f7fbb47e58c">

**Comment by Obs01ete** [comment]
Hi @yl-miao, thank you for your interest to GPTSwarm! Indeed, some couple of weeks ago, numpy==2.0 had been released and broke outstandingly many builds in the python world. We will consider adding a constraint of numpy<2 in the next version of GPTSwarm release. Meanwhile a hotfix is to manually install `pip install numpy==1.25.2` and possibly downgrade versions of packages like seaborn as needed. Please let me know if it solves the issue for you.

**Comment by Obs01ete** [comment]
@yl-miao you can always install the recent or your own customized version from the cloned repo with `poetry install`. Please find the instruction in https://github.com/metauto-ai/GPTSwarm/blob/main/DEVELOPMENT.md.
You can also try my latest fix at #27.

**Comment by yl-miao** [comment]
Hi, the #27 fixes this. Thank you very much : ) @Obs01ete
